from . import product_template_inherit
from . import sale_order_inherit
from . import manufacturing_inherit
from . import product_parent
from . import pallets_traceability
from . import stock_rule
from . import stock_move_inherit
from . import chemical_received_regulatory
from . import chemicals_produced_regulatory
from . import quality_control
from . import sop_regulatory
from . import change_production_qty_inherit
from . import res_partner_inherit