{
    'name': 'Organic Filling Solutions',
    'version': '1.1',
    'summary': 'Organic Filling Solutions',
    'sequence': 10,
    'description': """Organic Filling Solutions""",
    'category': 'Organic Filling Solutions',
    'website': 'https://www.odoo.com',
    'license': 'LGPL-3',
    'depends': ['base', 'contacts', 'stock', 'sale_management', 'product','account',
                'mrp','sale','uom','purchase_stock'],
    'data': [
        'data/sale_mail_template.xml',
        'security/ir.model.access.csv',
        'wizard/pallet_wizard.xml',
        'wizard/qc_wizard.xml',
        'data/parent_parent.xml',
        'data/pallet_data.xml',
        'report/packing_slip_template2.xml',
        'report/first_approve_report.xml',
        'report/first_approve_template2.xml',
        'report/packing_slip.xml',
        'report/quality_control.xml',
        'report/quality_control_template2.xml',
        'views/product_parent.xml',
        'views/manufacturing_inherit.xml',
        'views/mrp_button.xml',
        'views/sale_order.xml',
        'views/product_template_inherit.xml',
        'views/pallets_traceability.xml',
        'views/stock_move_inherit.xml',
        'views/stock_move_form.xml',
        'views/bom_form_inherit.xml',
        'views/stock_quant_inherit.xml',
        'views/regulatory.xml',
        'views/chemicals_produced.xml',
        'views/quality_control.xml',
        'views/sop_regulatory.xml',
        'views/res_partner_inherit.xml'
    ],
    'assets': {
        'web.assets_backend': [
        ],
        'web.assets_qweb': [
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
